$(document).ready
$('.img1').click(function(){ $('#display').load('images.html #img1') })
$('.img2').click(function(){ $('#display').load('images.html #img2') })
$('.img3').click(function(){ $('#display').load('images.html #img3') })
$('.img4').click(function(){ $('#display').load('images.html #img4') })
$('.img5').click(function(){ $('#display').load('images.html #img5') })
$('.img6').click(function(){ $('#display').load('images.html #img6') })
$('.img7').click(function(){ $('#display').load('images.html #img7') })
$('.img8').click(function(){ $('#display').load('images.html #img8') })
$('.img9').click(function(){ $('#display').load('images.html #img9') })
$('.img10').click(function(){ $('#display').load('images.html #img10') })

$('.img11').click(function(){ $('#display').load('images.html #img11') })
$('.img12').click(function(){ $('#display').load('images.html #img12') })
$('.img13').click(function(){ $('#display').load('images.html #img13') })
$('.img14').click(function(){ $('#display').load('images.html #img14') })
$('.img15').click(function(){ $('#display').load('images.html #img15') })
$('.img16').click(function(){ $('#display').load('images.html #img16') })
$('.img17').click(function(){ $('#display').load('images.html #img17') })
$('.img18').click(function(){ $('#display').load('images.html #img18') })
$('.img19').click(function(){ $('#display').load('images.html #img19') })
$('.img20').click(function(){ $('#display').load('images.html #img20') })

$('.img21').click(function(){ $('#display').load('images.html #img21') })
$('.img22').click(function(){ $('#display').load('images.html #img22') })
$('.img23').click(function(){ $('#display').load('images.html #img23') })
$('.img24').click(function(){ $('#display').load('images.html #img24') })
$('.img25').click(function(){ $('#display').load('images.html #img25') })
$('.img26').click(function(){ $('#display').load('images.html #img26') })
$('.img27').click(function(){ $('#display').load('images.html #img27') })
$('.img28').click(function(){ $('#display').load('images.html #img28') })
$('.img29').click(function(){ $('#display').load('images.html #img29') })
$('.img30').click(function(){ $('#display').load('images.html #img30') })

$('.stmore').click(function(){ $('.studautohide').show() })
$('.stless').click(function(){ $('.studautohide').hide() })

$('.enmore').click(function(){ $('.envautohide').show() })
$('.enless').click(function(){ $('.envautohide').hide() })

$('.lamore').click(function(){ $('.labautohide').show() })
$('.laless').click(function(){ $('.labautohide').hide() })

$('.detail').click(function(){ $(".detailed-info").show();$(".off-switch").show();$('.to-hide').hide()})
$('.less-detail').click(function(){ $('.detailed-info').hide(); $(".off-switch").hide(); $('.to-hide').show()})